# 1. Import the libraries and load the dataset


In [2]:
import numpy
import tensorflow
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.layers import Conv2D
from keras.optimizers import Adam
from keras.utils import np_utils

(x_train, y_train), (x_test, y_test)=mnist.load_data () #splitting the mnist data into train and test

# 2. Preprocess the data
print (x_train.shape)  #shape is used for give the dimens ion values #60000-rows 28x28-pixels
print (x_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [4]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [5]:
y_train[0]

5

In [8]:
x_train = x_train.reshape(60000,28,28,1).astype('float32')
x_test = x_test.reshape(10000,28,28,1).astype('float32')

In [9]:
number_of_classes=10
y_train = np_utils.to_categorical(y_train,number_of_classes)
y_test = np_utils.to_categorical(y_test,number_of_classes)

In [10]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

# Creating the model

In [11]:
model = Sequential()
model.add(Conv2D(64,(3,3),input_shape=(28,28,1), activation='relu'))
model.add(Conv2D(32,(3,3), activation='relu'))
model.add(Flatten())
model.add(Dense(number_of_classes,activation='softmax'))

# Observing the metrics

In [14]:
metrics = model.evaluate(x_test,y_test,verbose=0)
print("Metrics(test loss & Test Accuracy):")
print(metrics)

Metrics(test loss & Test Accuracy):
[0.13279657065868378, 0.9746000170707703]


In [15]:
prediction = model.predict(x_test[:4])
print(prediction)

1/1 [==============================] - 0s 141ms/step
[[3.2589063e-17 3.6806709e-26 7.8854779e-20 8.8341728e-14 1.9219707e-22
  1.2027587e-19 1.2524871e-24 1.0000000e+00 1.1770103e-18 1.2205606e-15]
 [1.4310128e-09 2.2385389e-13 1.0000000e+00 1.9885049e-20 3.4961761e-17
  5.1784157e-18 1.4508342e-08 3.2594468e-21 1.6639438e-13 2.9090641e-18]
 [5.3926308e-12 9.9999988e-01 2.4082918e-11 7.2773810e-16 1.1638223e-07
  4.2325346e-10 1.9166951e-11 2.8592819e-09 6.0266667e-11 1.3538813e-13]
 [1.0000000e+00 2.7968123e-23 1.2845692e-15 4.3967335e-22 4.6604858e-15
  2.3858796e-15 8.9479635e-10 1.0732235e-16 8.9632489e-18 5.4525480e-15]]


In [16]:
metrics = model.evaluate(x_test,y_test, verbose =0)
print("Metrics(Test loss & Test Accuracy):")
print(metrics)

Metrics(Test loss & Test Accuracy):
[0.13279657065868378, 0.9746000170707703]


In [17]:
prediction = model.predict(x_test[:4])
print(prediction)

1/1 [==============================] - 0s 24ms/step
[[3.2589063e-17 3.6806709e-26 7.8854779e-20 8.8341728e-14 1.9219707e-22
  1.2027587e-19 1.2524871e-24 1.0000000e+00 1.1770103e-18 1.2205606e-15]
 [1.4310128e-09 2.2385389e-13 1.0000000e+00 1.9885049e-20 3.4961761e-17
  5.1784157e-18 1.4508342e-08 3.2594468e-21 1.6639438e-13 2.9090641e-18]
 [5.3926308e-12 9.9999988e-01 2.4082918e-11 7.2773810e-16 1.1638223e-07
  4.2325346e-10 1.9166951e-11 2.8592819e-09 6.0266667e-11 1.3538813e-13]
 [1.0000000e+00 2.7968123e-23 1.2845692e-15 4.3967335e-22 4.6604858e-15
  2.3858796e-15 8.9479635e-10 1.0732235e-16 8.9632489e-18 5.4525480e-15]]


In [18]:
import numpy as np
print(np.argmax(prediction,axis=1))
print(y_test[:4])

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# Save the model

In [19]:
model.save('mnistCNN.h5')